### ISSUE TITLE
Update to 1.12.5

### ISSUE THREAD

**Issue by jeffreyguenther** [glebm/popper_js-rubygem#3]
It looks like the gem is a couple patch versions behind the javascript now. https://github.com/FezVrasta/popper.js/releases is showing the latest release at 1.12.5

Can you update the gem?

**Comment by glebm** [comment]
It's not behind, there are no JavaScript changes between v1.12.3 and v1.12.5: https://github.com/FezVrasta/popper.js/compare/v1.12.3...v1.12.5

**Comment by jeffreyguenther** [comment]
Is that because of the revert of the commit:

> Revert "fix(popper): Fixed regression #401 (#402)" (#408) …This reverts commit 1b3a82d.

**Comment by glebm** [comment]
I'm not sure but that seems likely.
