### ISSUE TITLE
You have requested:   popper_js ~> 1.12.3  The bundle currently has popper_js locked at 1.11.1

### ISSUE THREAD

**Issue by ghost** [glebm/popper_js-rubygem#4]
bundle install:
You have requested:
  popper_js ~> 1.12.3

The bundle currently has popper_js locked at 1.11.1.
Try running `bundle update popper_js`

and :

bundle update:
Bundler could not find compatible versions for gem "popper_js":
  In Gemfile:
    popper_js (~> 1.12.3) x64-mingw32

I did in GemFile:
gem 'popper_js', but why are these errors ?

**Comment by K4sku** [comment]
You have 
`popper_js (1.11.1)`
in your Gemlife.lock

I believe you have older version of bootstrap 4. The issue was resolved now, see https://github.com/twbs/bootstrap-rubygem/issues/109

You can update bootstrap. Change version in gemfile and run `bundle update bootstrap popper_js`.
