### ISSUE TITLE
update popper version?

### ISSUE THREAD

**Issue by jrochkind** [glebm/popper_js-rubygem#7]
The latest release of this gem seems to be for  popper 1.14.5. 

It seems that was released about a year ago, and there is now both a 1.14.6 and a 1.16.0. 

https://www.npmjs.com/package/popper.js

Thoughts on releasing with updated version?

**Comment by glebm** [comment]
Released v1.14.7, v1.15.0, and v1.16.0
https://rubygems.org/gems/popper_js

**Comment by jrochkind** [comment]
thanks!
