### ISSUE TITLE
Update to popper 2

### ISSUE THREAD

**Issue by kwent** [glebm/popper_js-rubygem#9]
## Update to popper 2

Cf. https://popper.js.org/docs/v2/migration-guide/
Cf. https://unpkg.com/@popperjs/core@2.5.4/dist/umd/popper.js

**Comment by Mindless999** [comment]
I would like to use Bootstrap V5 but that requires popper version2. I would like to see it updated to the latest version.

**Comment by glebm** [comment]
https://rubygems.org/gems/popper_js/versions/2.6.0
